#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May  4 17:03:25 2020

@author: mlcv
"""

import os
import sys
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [14, 8]

sys.path.append('../..')
from pytracking.analysis.plot_results import plot_results, print_results, print_per_sequence_results
from pytracking.evaluation import Tracker, get_dataset, trackerlist, Sequence
from pytracking.analysis.playback_results import playback_results

trackers = []
"""
trackers.extend(trackerlist('atom2_3d', 'default2_3d', range(0,1), 'ATOM'))
trackers.extend(trackerlist('atom2_3d', 'default', range(0,1), 'CFAM1'))
trackers.extend(trackerlist('atom2_3d', 'default1', range(0,1), 'CFAM2'))
# trackers.extend(trackerlist('atom2_3d', 'default2', range(0,1), 'CFAM3'))
trackers.extend(trackerlist('atom2_3d', 'default18', range(0,1), 'CFAM18_1'))
trackers.extend(trackerlist('atom2_3d', 'default18_1', range(0,1), 'CFAM18_2'))
trackers.extend(trackerlist('atom2_3d', 'default18_2', range(0,1), 'CFAM18_3'))
trackers.extend(trackerlist('atom2_3d', 'default18_3', range(0,1), 'CFAM18_4'))
trackers.extend(trackerlist('atom2_3d', 'default18_4', range(0,1), 'CFAM18_5'))
trackers.extend(trackerlist('atom2_3d', 'default18_5', range(0,1), 'CFAM18_6'))
# trackers.extend(trackerlist('atom2_3d', 'default18_50', range(0,1), 'CFAM18_7'))
trackers.extend(trackerlist('atom2_3d', 'default18_50_1', range(0,1), 'CFAM18_8'))
# trackers.extend(trackerlist('atom2_3d', 'default18_50_2', range(0,1), 'CFAM18_9'))
# trackers.extend(trackerlist('atom2_3d', 'trat18_35_0', range(0,1), 'AT18_0'))
# trackers.extend(trackerlist('atom2_3d', 'trat18_35_1', range(0,1), 'AT18_1'))
# trackers.extend(trackerlist('atom2_3d', 'trat18_35_2', range(0,1), 'AT18_2'))
# trackers.extend(trackerlist('atom2_3d', 'TRAT40_0', range(0,1), 'ATT18_40_0'))
# trackers.extend(trackerlist('atom2_3d', 'TRAT40_1', range(0,1), 'ATT18_40_1'))
trackers.extend(trackerlist('atom2_3d', 'TRAT40_2', range(0,1), 'ATT18_40_2'))
# trackers.extend(trackerlist('atom2_3d', 'TRAT40_3', range(0,1), 'ATT18_40_3'))
# trackers.extend(trackerlist('atom2_3d', 'TRAT40_4', range(0,1), 'ATT18_40_4'))
trackers.extend(trackerlist('atom2_3d', 'TRAT45_0', range(0,1), 'ATT18_45_0'))
trackers.extend(trackerlist('atom2_3d', 'TRAT45_1', range(0,1), 'ATT18_45_1'))
trackers.extend(trackerlist('atom2_3d', 'TRAT45_2', range(0,1), 'ATT18_45_2'))
trackers.extend(trackerlist('atom2_3d', 'TRAT45_3', range(0,1), 'ATT18_45_3'))
trackers.extend(trackerlist('atom2_3d', 'TRAT45_4', range(0,1), 'ATT18_45_4'))
# trackers.extend(trackerlist('Nfs', 'default2', range(0,1), 'CFAM2'))
# trackers.extend(trackerlist('Nfs', 'default', range(0,1), 'CFAM'))
# trackers.extend(trackerlist('Nfs', 'default1', range(0,1), 'CFAM1'))
# trackers.extend(trackerlist('Nfs', 'default3', range(0,3), '2_3d'))
# trackers.extend(trackerlist('uav', 'default2', range(0,1), 'CFAM2'))
# trackers.extend(trackerlist('uav', 'default', range(0,1), 'CFAM'))
# trackers.extend(trackerlist('uav', 'default1', range(0,1), 'CFAM1'))
# trackers.extend(trackerlist('uav', 'default3', range(0,1), '2_3d'))
# trackers.extend(trackerlist('LaSOT', 'default2', range(0,3), '2_3d1'))
# trackers.extend(trackerlist('LaSOT', 'default', range(0,3), '2_3d2'))
# trackers.extend(trackerlist('LaSOT', 'default3', range(0,3), '2_3d3'))
# trackers.extend(trackerlist('LaSOT', 'CFAM', range(0,1), 'CFAM'))
# trackers.extend(trackerlist('LaSOT', 'CFAM1', range(0,1), 'CFAM1'))
# trackers.extend(trackerlist('LaSOT', 'CFAM2', range(0,1), 'CFAM2'))
"""

# trackers.extend(trackerlist('atom3d_50_15', 'default', range(0,5), 'ATOM_50_15'))
# trackers.extend(trackerlist('atom3d_18_15_kens', 'default', range(0,5), 'atom3d_18_15_kens'))
# trackers.extend(trackerlist('atom3d_18_20_kens', 'default', range(0,5), 'atom3d_18_20_kens'))
# trackers.extend(trackerlist('atom2_3d', 'default', range(0,5), 'atom2_3d'))
# trackers.extend(trackerlist('atom2_3d', 'trat18_35', range(0,3), 'trat18_35'))
# trackers.extend(trackerlist('atom2_3d', 'TRAT40', range(0,3), 'TRAT40'))
# trackers.extend(trackerlist('atom2_3d', 'TRAT45', range(0,3), 'TRAT45'))
# trackers.extend(trackerlist('atom3d_ours_15', 'default', range(0,5), 'atom3d_ours_15'))
# trackers.extend(trackerlist('atom3d_ours_20', 'default', range(0,5), 'atom3d_ours_20'))
# trackers.extend(trackerlist('atom3d_ours_45', 'default', range(0,5), 'atom3d_ours_45'))
# trackers.extend(trackerlist('atom3d_ours_60', 'default', range(0,5), 'atom3d_ours_60'))
# trackers.extend(trackerlist('atom3d_ours_110_15', 'default', range(0,5), 'atom3d_ours_110_15'))
# trackers.extend(trackerlist('atom3d_ours_110_20', 'default', range(0,5), 'atom3d_ours_110_20'))
# trackers.extend(trackerlist('atom3d_18_4_15', 'default', range(0,5), 'atom3d_18_4_15'))
# trackers.extend(trackerlist('atom3d_18_4_20', 'default', range(0,5), 'atom3d_18_4_20'))
# trackers.extend(trackerlist('atom3d_18_4_60', 'default', range(0,5), 'atom3d_18_4_60'))
# trackers.extend(trackerlist('TRAT18_15_new', 'default', range(0,5), 'TRAT18_15_new'))
# trackers.extend(trackerlist('TRAT18_20_new', 'default', range(0,5), 'TRAT18_20_new'))
# trackers.extend(trackerlist('TRAT18_25_new', 'default', range(0,5), 'TRAT18_25_new'))
# trackers.extend(trackerlist('TRAT18_30_new', 'default', range(0,5), 'TRAT18_30_new'))
# trackers.extend(trackerlist('TRAT_18_60_18', 'default', range(0,5), 'TRAT_18_60_18'))
# trackers.extend(trackerlist('TRAT18_35_new', 'default', range(0,5), 'TRAT18_35_new'))
# trackers.extend(trackerlist('TRAT18_40_new', 'default', range(0,5), 'TRAT18_40_new'))
# trackers.extend(trackerlist('TRAT18_45_new', 'default', range(0,5), 'TRAT18_45_new'))
# trackers.extend(trackerlist('CFAM18_15_new', 'default', range(0,5), 'CFAM18_15_new'))
# trackers.extend(trackerlist('TRAT18_50_new', 'default', range(0,5), 'TRAT18_50_new'))
# trackers.extend(trackerlist('CFAM18_20_new', 'default', range(0,5), 'CFAM18_20_new'))
# trackers.extend(trackerlist('TRAT18_60_new', 'default', range(0,5), 'TRAT18_60_new'))
# trackers.extend(trackerlist('CFAM18_25_new', 'default', range(0,5), 'CFAM18_25_new'))
# trackers.extend(trackerlist('CFAM18_30_new', 'default', range(0,5), 'CFAM18_30_new'))
# trackers.extend(trackerlist('CFAM18_60_new', 'default', range(0,5), 'CFAM18_60_new'))
# trackers.extend(trackerlist('atom2_3d_18_60', 'default', range(0,5), 'atom2_3d_18_60'))
# trackers.extend(trackerlist('atom2_3d_eca_20', 'default', range(0,5), 'atom2_3d_eca_20'))
# trackers.extend(trackerlist('atom2_3d_eca_25', 'default', range(0,5), 'atom2_3d_eca_25'))
# trackers.extend(trackerlist('atom2_3d_eca_60', 'default', range(0,5), 'atom2_3d_eca_60'))
# trackers.extend(trackerlist('TRAT18_60_new_18', 'default', range(0,5), 'TRAT18_60_new_18'))
# trackers.extend(trackerlist('atom3dMF', 'default', range(0,5), 'ATOMMF_50_15'))
# trackers.extend(trackerlist('atom3dMF_12_15', 'default', range(0,5), 'ATOMMF_12_15'))
# trackers.extend(trackerlist('atom3dMF_60', 'default', range(0,5), 'ATOMMF_50_60'))
# trackers.extend(trackerlist('atom3d_20', 'default', range(0,5), 'ATOM3d_18_20'))
# trackers.extend(trackerlist('atom3d_25', 'default', range(0,5), 'ATOM3d_18_25'))
# trackers.extend(trackerlist('atom3d_30', 'default', range(0,5), 'ATOM3d_18_30'))
# trackers.extend(trackerlist('atom3d_35', 'default', range(0,5), 'ATOM3d_18_35'))
# trackers.extend(trackerlist('atom3d_40', 'default', range(0,5), 'ATOM3d_18_40'))
# trackers.extend(trackerlist('atom3d_45', 'default', range(0,5), 'ATOM3d_18_45'))
# trackers.extend(trackerlist('atom3d_50', 'default', range(0,5), 'ATOM3d_18_50'))
# trackers.extend(trackerlist('atom3d_50_20', 'default', range(0,5), 'ATOM3d_50_20'))
# trackers.extend(trackerlist('atom3d_50_25', 'default', range(0,5), 'ATOM3d_50_25'))
# trackers.extend(trackerlist('atom3d_50_30', 'default', range(0,5), 'ATOM3d_50_30'))
# trackers.extend(trackerlist('atom3d_50_35', 'default', range(0,5), 'ATOM3d_50_35'))
# trackers.extend(trackerlist('atom3d_50_40', 'default', range(0,5), 'ATOM3d_50_40'))
# trackers.extend(trackerlist('atom3d_50_45', 'default', range(0,5), 'ATOM3d_50_45'))
# trackers.extend(trackerlist('atom3d_50_50', 'default', range(0,5), 'ATOM3d_50_50'))
# trackers.extend(trackerlist('atom3d_50_55', 'default', range(0,5), 'ATOM3d_50_55'))
# trackers.extend(trackerlist('atom3d_50_60', 'default', range(0,5), 'ATOM3d_50_60'))
# trackers.extend(trackerlist('atom3d_50_25', 'default', range(0,5), 'ATOM3d_50Best'))
# trackers.extend(trackerlist('atom3d_50', 'default', range(0,5), 'ATOM3d_18Best'))
# trackers.extend(trackerlist('atom2_3d_otb_uav_nfs', 'default', range(0,5), 'atom2_3d_otb_uav_nfs'))
# trackers.extend(trackerlist('TRATCNNSF25', 'default', range(0,5), 'TRATCNNSF25'))
# trackers.extend(trackerlist('TRATCNNSF30', 'default', range(0,5), 'TRATCNNSF30'))
# trackers.extend(trackerlist('TRATCNNSF', 'default', range(0,5), 'TRATCNNSF'))
# trackers.extend(trackerlist('TRATSF', 'default', range(0,5), 'TRATSF'))
# trackers.extend(trackerlist('dimp3d', 'dimp50', range(0,5), 'dimp3d_R50'))
# trackers.extend(trackerlist('dimp', 'dimp18', range(0,5), 'dimp_R18'))
# trackers.extend(trackerlist('dimp', 'dimp50', range(0,5), 'dimp_R50'))
# trackers.extend(trackerlist('dimpSF', 'dimp50', range(0,5), 'dimpSF_R50'))
# trackers.extend(trackerlist('dimpSFAttn', 'dimp50', range(0,5), 'dimpSFAttn_R50'))
# trackers.extend(trackerlist('dimpSF2F', 'dimp50', range(0,5), 'dimpSF2F'))
# trackers.extend(trackerlist('dimpFMFAttn', 'dimp50', range(0,5), 'dimpFMFAttn'))
# trackers.extend(trackerlist('dimpFMFConAttn', 'dimp50', range(0,5), 'dimpFMFConAttn'))
# trackers.extend(trackerlist('dimpFMFZipAttn', 'dimp50', range(0,5), 'dimpFMFZipAttn'))
# trackers.extend(trackerlist('dimpFMFAttn_k3', 'dimp50', range(0,5), 'dimpFMFAttn_k3'))
# trackers.extend(trackerlist('dimpFMFAttnAw', 'dimp50', range(0,3), 'dimpFMFAttnAw_48'))
# trackers.extend(trackerlist('dimpFMFAttnAw_k5_50', 'dimp50', range(0,5), 'dimpFMFAttnAw_k5'))
# trackers.extend(trackerlist('dimpFMF', 'dimp50', range(0,5), 'dimpFMF'))
# trackers.extend(trackerlist('dimpFMFAttnAw', 'dimp50_45', range(0,3), 'dimp50_45'))
# trackers.extend(trackerlist('dimpFMFAttnAw', 'dimp50_46', range(0,3), 'dimp50_46'))
# trackers.extend(trackerlist('dimpFMFAttnAw', 'dimp50_47', range(0,3), 'dimp50_47'))
# trackers.extend(trackerlist('dimpFMFAttnAw', 'dimp50_48', range(0,3), 'dimp50_48'))
trackers.extend(trackerlist('Ranking', 'default', range(1,2), 'Ranking'))
# trackers.extend(trackerlist('Ranking_aspect', 'default', range(0,3), 'Ranking_aspect'))


# trackers.extend(trackerlist('trat', 'default', range(0,5), 'TRAT_R50'))
# trackers.extend(trackerlist('trat_CF', 'default', range(0,5), 'TRAT_R50_CF_sum'))
# trackers.extend(trackerlist('trat_CF_average', 'default', range(0,5), 'TRAT_R50_CF_average'))
# trackers.extend(trackerlist('trat_CF_attn_ECA_k3', 'default', range(0,5), 'TRAT_R50_CF_ECA_k3'))
# trackers.extend(trackerlist('trat_CF_attn_last', 'default', range(0,5), 'TRAT_R50_CF_ECA_last'))
# trackers.extend(trackerlist('TRATSF', 'default', range(0,5), 'TRATSF_R50'))
# trackers.extend(trackerlist('TRATSFAttn_Eca_R50_k5_dimp', 'default', range(0,5), 'TRATSFAttn_Eca_R50_k5_dimp'))
# trackers.extend(trackerlist('TRATSFAttn_k3', 'default', range(0,5), 'TRATSFAttn_Eca_R50_k3'))
# trackers.extend(trackerlist('TRATSFAttn_k5', 'default', range(0,5), 'TRATSFAttn_Eca_R50_k5'))
# trackers.extend(trackerlist('TratCatAttn_AllTrained', 'default', range(0,5), 'TratCatAttn_AllTrained'))
# trackers.extend(trackerlist('TratCatAttn_Trained', 'default', range(0,5), 'TratCatAttn'))
# trackers.extend(trackerlist('TratCatAttn_LR0.0075', 'default', range(0,5), 'TratCatAttn_LR0.0075'))
# trackers.extend(trackerlist('TratCatAttn32_LR-085-115', 'default', range(0,5), 'TratCatAttn32_LR-085'))
# trackers.extend(trackerlist('TratCatAttn32_LR-085-115', 'default2', range(0,5), 'TratCatAttn32_LR-115'))
# trackers.extend(trackerlist('TratCatAttn31-32', 'default2', range(0,5), 'TratCatAttn32'))
#trackers.extend(trackerlist('TratCatAttnSA4.5-5.5', 'default', range(0,5), 'TratCatAttnSA4.5'))
#trackers.extend(trackerlist('TratCatAttn32-SA4.5-BRiter3-15', 'default', range(0,5), 'TratCatAttn32-SA4.5-BRiter3'))
#trackers.extend(trackerlist('TratCatAttn32-SA4.5-BRiter3-15', 'default2', range(0,5), 'TratCatAttn32-SA4.5-BRiter15'))
#trackers.extend(trackerlist('TratCatAttnSA4.5-TS5-HNTHR0.1-0.9', 'default', range(0,5), 'TratCatAttnSA4.5-TS5-HNTHR0.1'))
# trackers.extend(trackerlist('Ranking', 'Results_HR', range(0,1), 'Results_HR'))
# trackers.extend(trackerlist('Ranking', 'Results_deneme_new', range(0,1), 'Ranking'))
# trackers.extend(trackerlist('Ranking', 'HR_OTB', range(0,1), 'HR_OTB51'))

# trackers.extend(trackerlist('Ranking', 'Results_HR', range(0,1), 'Results_HR'))
# trackers.extend(trackerlist('Ranking', 'defaultold', range(0,1), 'RankingFast'))
# trackers.extend(trackerlist('dimpRank', 'dimpRank18', range(0,1), 'dimpRank18'))
# trackers.extend(trackerlist('dimpRank', 'dimpRank50_search', range(2,3), 'dimpRank50'))
trackers.extend(trackerlist('MDNet', 'default', range(4,5), 'MDNet'))

# trackers.extend(trackerlist('RFSF_deneme', 'default', range(0,3), 'RFSF_deneme'))
# trackers.extend(trackerlist('RFSF', 'default', range(0,3), 'RFSF19'))
# trackers.extend(trackerlist('RFSF', 'default2', range(0,3), 'RFSF28'))

# # trackers.extend(trackerlist('RFAF_old', 'default', range(0,1), 'RFAF'))
# trackers.extend(trackerlist('Ranking_old', 'default', range(0,3), 'NoR'))
# trackers.extend(trackerlist('Ranking_old', 'default2', range(0,5), 'Ranking'))
# trackers.extend(trackerlist('Ranking_old', 'default3', range(0,5), 'H_Ranking'))
# trackers.extend(trackerlist('RankingFlow', '50_default2', range(0,3), 'RankingFlow50'))
# trackers.extend(trackerlist('RankingFlow', 'default', range(0,3), 'RankingFlow150'))
# trackers.extend(trackerlist('RankingFlow', 'default2', range(0,3), 'RankingFlow100'))

# trackers.extend(trackerlist('HR_72', 'default', range(0,5), 'HR_72'))
# trackers.extend(trackerlist('HR_32', 'default', range(0,5), 'HR_32'))
# trackers.extend(trackerlist('R_32', 'default', range(0,5), 'R_32'))
# trackers.extend(trackerlist('NoR_32', 'default', range(0,5), 'NoR_32'))
# trackers.extend(trackerlist('TratCatAttn_Sascale4', 'default', range(0,5), 'TratCatAttn_Sascale4'))
# trackers.extend(trackerlist('TratCatAttn_Moreiter', 'default', range(0,5), 'TratCatAttn_Moreiter'))
# trackers.extend(trackerlist('TRATCNNSF40', 'default', range(0,5), 'TRATCNNSF40'))
# trackers.extend(trackerlist('TRATCNNSF45', 'default', range(0,5), 'TRATCNNSF45'))
# trackers.extend(trackerlist('TRATCNNSF50', 'default', range(0,5), 'TRATCNNSF50'))
# trackers.extend(trackerlist('TRATCNNSF55', 'default', range(0,5), 'TRATCNNSF55'))
# trackers.extend(trackerlist('TRATCNNSF60', 'default', range(0,5), 'TRATCNNSF60'))
# trackers.extend(trackerlist('atom_R50_ours', 'default', range(0,5), 'atom_50_ours'))
# trackers.extend(trackerlist('atom_R50_CBAM', 'default', range(0,5), 'atom_50CBAM'))
# trackers.extend(trackerlist('atom_dimp', 'default', range(0,5), 'atom_dimp'))
# trackers.extend(trackerlist('atom', 'default', range(0,5), 'atom_paper'))
# trackers.extend(trackerlist('atom2_3d_otb_uav_nfs_lasot', 'default', range(0,5), 'atom2_3d_otb_uav_nfs_lasot'))
# trackers.extend(trackerlist('atom3d', 'default', range(0,5), 'atom3d_R50'))

filter_criteria = None
dataset = get_dataset('otb')
# sequence = [dataset['Basketball']]
print_per_sequence_results(trackers, dataset, 'otb', merge_results=True, filter_criteria=filter_criteria, force_evaluation=False)
# playback_results(trackers, sequence[0])
 
plot_results(trackers, dataset, 'otb', merge_results=True, plot_types=('success', 'prec'), 
              skip_missing_seq=False, force_evaluation=True, plot_bin_gap=0.05, exclude_invalid_frames=False)
print_results(trackers, dataset, 'otb', merge_results=True, plot_types=('success', 'prec'))

